#!/usr/bin/python3
import py_compile
import os

_file = os.environ.get('PYFILE')
if not _file:
    exit(1)

res_file = f'{_file}c'
py_compile.compile(_file, cfile=res_file, optimize=2)
print(f"Compiling {_file} ...")
